### ISSUE TITLE
There is something wrong with transitive_closure.py

### ISSUE THREAD

**Issue by JiajunHuang1999** [facebookresearch/poincare-embeddings#50]
I have trouble when running as the readme suggests transitive_closure.py. Please help me figure it out. Thanks:
(poincare) jiajunhuang@jiajunhuang-Ubantu01:~/poincare-embeddings/wordnet$ python transitive_closure.py
Traceback (most recent call last):
  File "transitive_closure.py", line 14, in <module>
    wn.all_synsets
  File "/home/jiajunhuang/anaconda3/envs/poincare/lib/python3.6/site-packages/nltk/corpus/util.py", line 123, in __getattr__
    self.__load()
  File "/home/jiajunhuang/anaconda3/envs/poincare/lib/python3.6/site-packages/nltk/corpus/util.py", line 83, in __load
    root = nltk.data.find('{}/{}'.format(self.subdir, self.__name))
  File "/home/jiajunhuang/anaconda3/envs/poincare/lib/python3.6/site-packages/nltk/data.py", line 673, in find
    return find(modified_name, paths)
  File "/home/jiajunhuang/anaconda3/envs/poincare/lib/python3.6/site-packages/nltk/data.py", line 660, in find
    return ZipFilePathPointer(p, zipentry)
  File "/home/jiajunhuang/anaconda3/envs/poincare/lib/python3.6/site-packages/nltk/compat.py", line 228, in _decorator
    return init_func(*args, **kwargs)
  File "/home/jiajunhuang/anaconda3/envs/poincare/lib/python3.6/site-packages/nltk/data.py", line 506, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/home/jiajunhuang/anaconda3/envs/poincare/lib/python3.6/site-packages/nltk/compat.py", line 228, in _decorator
    return init_func(*args, **kwargs)
  File "/home/jiajunhuang/anaconda3/envs/poincare/lib/python3.6/site-packages/nltk/data.py", line 1055, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/home/jiajunhuang/anaconda3/envs/poincare/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/home/jiajunhuang/anaconda3/envs/poincare/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by lematt1991** [comment]
Can you run the following in a python interpreter:

```Python
import nltk
nltk.download('wordnet')
```

**Comment by lematt1991** [comment]
Closing due to inactivity.
