### ISSUE TITLE
When I run "python setup.py build_ext --inplace", some problems occur

### ISSUE THREAD

**Issue by Madrid-Ista** [facebookresearch/poincare-embeddings#62]
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    out = check_output([CC, '--version'])
  File "C:\ProgramData\Anaconda3\envs\poincare\lib\subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "C:\ProgramData\Anaconda3\envs\poincare\lib\subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\ProgramData\Anaconda3\envs\poincare\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\envs\poincare\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by qimg412** [comment]
> 
hello,I met this bug when I run it,too,But how to add the code for VS_2019?
