### ISSUE TITLE
ValueError: Buffer dtype mismatch, expected 'long_t' but got 'long'

### ISSUE THREAD

**Issue by martinthewhale** [facebookresearch/poincare-embeddings#73]
Hi,

When trying to run
```powershell
python embed.py -dim 5 -lr 0.3 -epochs 300 -negs 50 -burnin 20 -ndproc 4 -model distance -manifold poincare -dset wordnet/mammal_closure.csv -che
ckpoint mammals.pth -batchsize 10 -eval_each 1 -fresh -sparse -train_threads 2
```
as provided in `train_mammals.sh`, I run into this error:
```
Traceback (most recent call last):
  File "embed.py", line 264, in <module>
    main()
  File "embed.py", line 162, in main
    data = BatchedDataset(idx, objects, weights, opt.negs, opt.batchsize,
  File "hype\graph_dataset.pyx", line 75, in hype.graph_dataset.BatchedDataset.__cinit__
    self._mk_weights(idx, weights)
  File "hype\graph_dataset.pyx", line 83, in hype.graph_dataset.BatchedDataset._mk_weights
    def _mk_weights(self, npc.ndarray[npc.long_t, ndim=2] idx, npc.ndarray[npc.double_t, ndim=1] weights):
ValueError: Buffer dtype mismatch, expected 'long_t' but got 'long'
```
Should I modify the `graph_dataset.pyx` file?

**Comment by martinthewhale** [comment]
Switch to Linux with GCC and everything works fine.
